= ipa

image:https://travis-ci.org/SUSE/ipa.svg?branch=master["Build Status", link="https://travis-ci.org/SUSE/ipa"]

*ipa* (Image Proofing App)

== overview

*ipa* provides a command line utility to test images in the
Public Cloud (AWS, Azure, GCE, etc.).

=== Installation

To install the package use the following commands as root:

[source]
----
zypper ar http://download.opensuse.org/repositories/Cloud:/Tools/<distribution>
zypper refresh
zypper in python-ipa
----

=== Requirements

* azurectl
* boto3
* Click
* paramiko
* pytest
* PyYaml
* testinfra

=== Config

The framework config is ini format ~/.config/ipa/config. Anything
specific to the test framework can be found in this file. Thus anything
that is cloud framework independent such as the test dir and results dir.

[source,ini]
----
[ipa]
tests=~/ipa/tests/
results=~/ipa/results/

[ec2]
region=us-west-1
----

=== Azure Config

*ipa* shares the azurectl config file. See the
link:https://github.com/SUSE/azurectl#configuration-file[azurectl readme] for
more info on the location and format.

=== EC2 Config

For testing EC2 instances *ipa* will use the ec2utils config file located at
~/.ec2utils.conf. See
link:https://github.com/SUSE/Enceladus/tree/master/ec2utils[ec2utils] for an
example config file.

=== Tests

*ipa* uses the Testinfra package for writing unit tests. Testinfra leverages
Pytest and provides modules such as Package, Process and Service to test the
state of images. See the
link:https://testinfra.readthedocs.io/en/latest/[Testinfra Docs] for more
information on writing infrastructure tests.

[NOTE]
====
*ipa* currently passes the Pytest option `-x` (stop on first failure) through
as `--early-exit`. If there's an interest or need for any other options/args
please submit an issue to link:https://github.com/SUSE/ipa/issues[Github].
====

=== CLI Overview

The CLI provides multiple subcommands to initiate image testing:

`ipa test`::
Test image in the given framework using the supplied test files.

`ipa results`::
Print test results info.

`ipa list`::
Print a list of test files or test cases.

=== Issues/Enhancements

Please submit issues and requests to
link:https://github.com/SUSE/ipa/issues[Github].

=== Contributing

Contributions to *ipa* are welcome and encouraged.
See link:CONTRIBUTING.asciidoc[CONTRIBUTING] for info on getting started.

=== License

Copyright (c) 2017 SUSE LLC.

Distributed under the terms of GPL-3.0 license, see
link:LICENSE[LICENSE] for details.
