.TH "IMG-PROOF TEST" "1" "29-May-2019" "" "img-proof test Manual"
.SH NAME
img-proof\-test \- Test image in the given framework using the...
.SH SYNOPSIS
.B img-proof test
[OPTIONS] [azure|ec2|gce|ssh] [TESTS]...
.SH DESCRIPTION
Test image in the given framework using the supplied test files.
.SH OPTIONS
.TP
\fB\-\-accelerated\-networking\fP
Enable accelerated networking in Azure instance network interface.
.TP
\fB\-\-access\-key\-id\fP TEXT
EC2 access key ID for login credentials.
.TP
\fB\-a,\fP \-\-account TEXT
Settings account to provide connection information.
.TP
\fB\-\-cleanup\fP / \-\-no\-cleanup
Terminate instance after tests. By default an instance will be deleted on success and left running if there is a test failure.
.TP
\fB\-C,\fP \-\-config PATH
img_proof config file location. Default: ~/.config/img_proof/config
.TP
\fB\-D,\fP \-\-description TEXT
Short description for test run.
.TP
\fB\-d,\fP \-\-distro [opensuse_leap|sles]
The distribution of the image.
.TP
\fB\-\-early\-exit\fP
Terminate test suite on first failure.
.TP
\fB\-h,\fP \-\-history\-log PATH
img_proof history log file location. Default: ~/.config/img_proof/.history
.TP
\fB\-i,\fP \-\-image\-id TEXT
The ID of the image used for instance.
.TP
\fB\-\-inject\fP PATH
Path to an injection yaml config file.
.TP
\fB\-t,\fP \-\-instance\-type TEXT
Instance type to use for launching machine.
.TP
\fB\-\-ip\-address\fP TEXT
IP address for the test instance (only used by SSH cloud).
.TP
\fB\-\-debug\fP
Display debug level logging to console.
.TP
\fB\-\-verbose\fP
(Default) Display logging info to console.
.TP
\fB\-\-quiet\fP
Silence logging information on test run.
.TP
\fB\-\-no\-default\-test\-dirs\fP
Do not include default test directories in search for tests.
.TP
\fB\-\-cloud\-config\fP TEXT
The cloud specific config file location.
.TP
\fB\-\-region\fP TEXT
Cloud region to test image.
.TP
\fB\-\-results\-dir\fP TEXT
Directory to store test results and output.
.TP
\fB\-R,\fP \-\-running\-instance\-id TEXT
The ID or Name of running instance to test.
.TP
\fB\-\-secret\-access\-key\fP TEXT
EC2 secret access key for login credentials.
.TP
\fB\-\-security\-group\-id\fP TEXT
EC2 security group id to assign to instances VPC.
.TP
\fB\-\-service\-account\-file\fP TEXT
GCE service account file for login credentials.
.TP
\fB\-\-ssh\-key\-name\fP TEXT
Optional SSH private key-pair name for EC2.
.TP
\fB\-\-ssh\-private\-key\-file\fP PATH
SSH private key file for accessing instance.
.TP
\fB\-u,\fP \-\-ssh\-user TEXT
SSH user for accessing instance.
.TP
\fB\-\-subnet\-id\fP TEXT
Subnet to launch the new instance into.
.TP
\fB\-\-test\-dirs\fP TEXT
Directories to search for tests.
.TP
\fB\-\-timeout\fP INTEGER RANGE
The time to wait when establishing an SSH connection and for instances to change state.
.TP
\fB\-\-vnet\-name\fP TEXT
Azure virtual network name to attach network interface.
.TP
\fB\-\-vnet\-resource\-group\fP TEXT
Azure resource group name where virtual network is found.
.TP
\fB\-\-collect\-vm\-info\fP
Controls whether general info about VM in cloud should be collected
