.TH "IMG-PROOF" "1" "29-May-2019" "" "img-proof Manual"
.SH NAME
img-proof \- img-proof provides a Python API and command...
.SH SYNOPSIS
.B img-proof
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
img-proof provides a Python API and command line utility for testing images.
.PP
It can be used to test images in the Public Cloud (AWS, Azure, GCE, etc.).
.SH OPTIONS
.TP
\fB\-\-version\fP
Show the version and exit.
.TP
\fB\-\-license\fP
Show license information and exit.
.TP
\fB\-\-no\-color\fP
Remove ANSI color and styling from output.
.SH COMMANDS
.PP
\fBlist\fP
  Print a list of test files or test cases.
  See \fBimg-proof-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBresults\fP
  Process provided history log and results...
  See \fBimg-proof-results(1)\fP for full documentation on the \fBresults\fP command.
.PP
\fBtest\fP
  Test image in the given framework using the...
  See \fBimg-proof-test(1)\fP for full documentation on the \fBtest\fP command.
