.TH "IPA LIST" "1" "31-Jul-2017" "" "ipa list Manual"
.SH NAME
ipa\-list \- Print a list of test files or test cases.
.SH SYNOPSIS
.B ipa list
[OPTIONS]
.SH DESCRIPTION
Print a list of test files or test cases.

If verbose option selected, print all tests cases in
each test file, otherwise print the test files only.