.TH "IPA LIST" "1" "31-May-2018" "" "ipa list Manual"
.SH NAME
ipa\-list \- Print a list of test files or test cases.
.SH SYNOPSIS
.B ipa list
[OPTIONS] [TEST_DIRS]...
.SH DESCRIPTION
Print a list of test files or test cases.
.PP
If verbose option selected, print all tests cases in
each test file, otherwise print the test files only.
.PP
If test_dirs supplied they will be used to search for
tests otherwise the default test directories are used.
.SH OPTIONS
.TP
\fB\-v,\fP \-\-verbose
.PP